'''
Author: Veerendra.Kakumanu
Description: HTTP status codes (Collected from wikipedia)
Format: <CODE>:[<TAG NAME>, <DESCRIPTION>]
'''
codes={
"100" : ["Continue","The server has received the request headers and the client should proceed to send the request body [in the case of a request for which a body needs to be sent"],
"101" : ["Switching Protocols","The requester has asked the server to switch protocols and the server has agreed to do so"],
"102" : ["Processing","The server has received and is processing the request, but no response is available yet"],
"200" : ["OK","Successful HTTP requests"],
"201" : ["Created","The request has been fulfilled, resulting in the creation of a new resource"],
"202" : ["Accepts","The request has been accepted for processing, but the processing has not been completed"],
"203" : ["Non-Authoritative Information","The server is a transforming proxy that received a 200 OK from its origin, but is returning a modified version of the origin's response"],
"204" : ["No Content","The server successfully processed the request and is not returning any content"],
"205" : ["Reset Content","The server successfully processed the request, but is not returning any content"],
"206" : ["Partial Content","The server is delivering only part of the resource [byte serving] due to a range header sent by the client"],
"207" : ["Multi-Status","The message body that follows is an XML message and can contain a number of separate response codes, depending on how many sub-requests were made"],
"208" : ["Already Reported","The members of a DAV binding have already been enumerated in a previous reply to this request, and are not being included again"],
"226" : ["IM Used","The server has fulfilled a request for the resource, and the response is a representation of the result of one or more instance-manipulations applied to the current instance"],
"300" : ["Moved Permanently","This and all future requests should be directed to the given URI"],
"302" : ["Found","The client to perform a temporary redirect/Moved Temporarily"],
"303" : ["See Other", "The response to the request can be found under another URI using a GET method"],
"304" : ["Not Modified","The resource has not been modified since the version specified by the request headers If-Modified-Since or If-None-Match"],
"305" : ["Use Proxy","The requested resource is available only through a proxy, the address for which is provided in the response"],
"306" : ["Switch Proxy","Subsequent requests should use the specified proxy"],
"307" : ["Temporary Redirect","The request should be repeated with another URI; however, future requests should still use the original URI"],
"308" : ["Permanent Redirect","The request and all future requests should be repeated using another URI"],
"400" : ["Bad Request","The server cannot or will not process the request due to an apparent client error [e.g., malformed request syntax]"],
"401" : ["Unauthorized","Authentication is required and has failed or has not yet been provided"],
"402" : ["Payment Required","Digital cash or micropayment scheme[but that has not happened]"],
"403" : ["Forbidden","The request was valid, but the server is refusing action. The user might not have the necessary permissions for a resource, or may need an account of some sort."],
"404" : ["Not Found", "The requested resource could not be found but may be available in the future. Subsequent requests by the client are permissible."],
"405" : ["Method Not Allowed","A request method is not supported for the requested resource; for example, a GET request on a form which requires data to be presented via POST, or a PUT request on a read-only resource"],
"406" : ["Not Acceptable","The requested resource is capable of generating only content not acceptable according to the Accept headers sent in the request"],
"407" : ["Proxy Authentication Required","The client must first authenticate itself with the proxy"],
"408" : ["Request Time-out","The server timed out waiting for the request"],
"407" : ["Conflict","The request could not be processed because of conflict in the request, such as an edit conflict between multiple simultaneous updates"],
"410" : ["Gone","The resource requested is no longer available and will not be available again"],
"411" : ["Length Required","The request did not specify the length of its content, which is required by the requested resource"],
"412" : ["Precondition Failed","The server does not meet one of the preconditions that the requester put on the request"],
"413" : ["Payload Too Large","The request is larger than the server is willing or able to process"],
"414" : ["URI Too Long","The URI provided was too long for the server to process"],
"415" : ["Unsupported Media Type","The request entity has a media type which the server or resource does not support"],
"416" : ["Range Not Satisfiable","The client has asked for a portion of the file [byte serving], but the server cannot supply that portion"],
"417" : ["Expectation Failed","The server cannot meet the requirements of the Expect request-header field"],
"418" : ["I'm a teapot", "The RFC specifies this code should be returned by teapots requested to brew coffee"],
"421" : ["Misdirected Request","The request was directed at a server that is not able to produce a response"],
"422" : ["Unprocessable Entity","The request was well-formed but was unable to be followed due to semantic errors"],
"423" : ["Locked","The resource that is being accessed is locked"],
"424" : ["Failed Dependency","The request failed due to failure of a previous request"],
"426" : ["Upgrade Required","The client should switch to a different protocol such as TLS/1.0, given in the Upgrade header field"],
"428" : ["Precondition Required","The origin server requires the request to be conditional. Intended to prevent the 'lost update' problem"],
"429" : ["Too Many Requests","The user has sent too many requests in a given amount of time. Intended for use with rate-limiting schemes"],
"431" : ["Request Header Fields Too Large","The server is unwilling to process the request because either an individual header field, or all the header fields collectively, are too large"],
"451" : ["Unavailable For Legal Reasons","A server operator has received a legal demand to deny access to a resource or to a set of resources that includes the requested resource"],
"500" : ["Internal Server Error","Unexpected condition was encountered and no more specific message is suitable"],
"501" : ["Not Implemented","The server either does not recognize the request method, or it lacks the ability to fulfill the request"],
"502" : ["Bad Gateway","The server was acting as a gateway or proxy and received an invalid response from the upstream server"],
"503" : ["Service Unavailable","The server is currently unavailable [because it is overloaded or down for maintenance]. Generally, this is a temporary state"],
"504" : ["Gateway Time-out","The server was acting as a gateway or proxy and did not receive a timely response from the upstream server"],
"505" : ["HTTP Version Not Supported","The server does not support the HTTP protocol version used in the request"],
"506" : ["Variant Also Negotiates","Transparent content negotiation for the request results in a circular reference"],
"507" : ["Insufficient Storage","The server is unable to store the representation needed to complete the request"],
"508" : ["Loop Detected","The server detected an infinite loop while processing the request"],
"510" : ["Not Extended","Further extensions to the request are required for the server to fulfill it"],
"511" : ["Network Authentication Required","The client needs to authenticate to gain network access"],
"103" : ["Checkpoint/Early Hints","The resumable requests proposal to resume aborted PUT or POST requests/return some response headers before entire HTTP response"],
"419" : ["I'm a fox","Returned by some versions of Smoothwall and Foxwall firewall systems when a config test is returned"],
"420" : ["Method Failure","Deprecated response used by the Spring Framework when a method has failed"],
"420" : ["Enhance Your Calm [Twitter]","Returned by version 1 of the Twitter Search and Trends API when the client is being rate limited"],
"450" : ["Blocked by Windows Parental Controls [Microsoft]","Windows Parental Controls are turned on and are blocking access to the given webpage"],
"498" : ["Invalid Token [Esri]","Expired or otherwise invalid token [Returned by ArcGIS for Server]"],
"499" : ["Token Required [Esri]","A token is required but was not submitted [Returned by ArcGIS for Server]"],
"499" : ["Request has been forbidden by antivirus","Produced by some programs such as Wget when a malicious site is intercepted"],
"509" : ["Bandwidth Limit Exceeded [Apache Web Server/cPanel]","The server has exceeded the bandwidth specified by the server administrator"],
"530" : ["Site is frozen","A Site that has been frozen due to inactivity [Used by the Pantheon web platform]"],
"598" : ["Network read timeout error","Signals a network read timeout behind the proxy to a client in front of the proxy"],
"599" : ["Network connect timeout error","The connection to the network times out"],
"440" : ["Login Time-out","The client's session has expired and must log in again"],
"449" : ["Retry With","The server cannot honour the request because the user has not provided the required information"],
"451" : ["Redirect","A more efficient server is available or the server cannot access the users' mailbox [Used in Exchange ActiveSync]"],
"444" : ["No Response/nginx","The server has returned no information to the client and closed the connection"],
"495" : ["SSL Certificate Error/nginx","The client has provided an invalid client certificate"],
"496" : ["SSL Certificate Required/nginx","Client certificate is required but not provided"],
"497" : ["HTTP Request Sent to HTTPS Port/nginx","The client has made a HTTP request to a port listening for HTTPS requests"],
"499" : ["Client Closed Request/nginx","The client has closed the request before the server could send a response"],
"520" : ["Unknown Error/Cloudflare","Catch-all response for when the origin server returns something unexpected"],
"521" : ["Web Server Is Down/Cloudflare","The origin server has refused the connection from Cloudflare"],
"522" : ["Connection Timed Out/Cloudflare","Cloudflare could not negotiate a TCP handshake with the origin server"],
"523" : ["Origin Is Unreachable/Cloudflare","Cloudflare could not reach the origin server"],
"524" : ["A Timeout Occurred/Cloudflare","Cloudflare was able to complete a TCP connection to the origin server, but did not receive a timely HTTP response"],
"525" : ["SSL Handshake Failed/Cloudflare","Cloudflare could not negotiate a SSL/TLS handshake with the origin server"],
"526" : ["Invalid SSL Certificate/Cloudflare","Cloudflare could not validate the SSL/TLS certificate that the origin server presented"],
"527" : ["Railgun Error/Cloudflare","The requests timeout or failed after the WAN connection has been established"]
}
